#!/usr/bin/env bash
# Shared helpers for runtime-e2e tests.
# Source this from each test.sh: source "$SCRIPT_DIR/../_lib/common.sh"
#
# Reads eval-tier credentials from /tmp/axonflow-e2e-env.sh if available
# (generated by axonflow-enterprise/scripts/setup-e2e-testing.sh evaluation).

set -euo pipefail

if [ -f /tmp/axonflow-e2e-env.sh ]; then
  source /tmp/axonflow-e2e-env.sh
fi

: "${AXONFLOW_ENDPOINT:=http://localhost:8080}"
: "${AXONFLOW_CLIENT_ID:=demo-client}"
: "${AXONFLOW_CLIENT_SECRET:=demo-secret}"
: "${AXONFLOW_AUTH:=$(echo -n "${AXONFLOW_CLIENT_ID}:${AXONFLOW_CLIENT_SECRET}" | base64)}"
: "${AXONFLOW_USER_TOKEN:=anonymous}"
: "${LLM_MODEL:=ollama/llama3.2}"
: "${AXONFLOW_TELEMETRY:=off}"
: "${AXONFLOW_DB_HOST:=localhost}"
: "${AXONFLOW_DB_PORT:=5432}"
: "${AXONFLOW_DB_USER:=axonflow}"
: "${AXONFLOW_DB_PASSWORD:=localdev123}"
: "${AXONFLOW_DB_NAME:=axonflow}"

export AXONFLOW_ENDPOINT AXONFLOW_CLIENT_ID AXONFLOW_CLIENT_SECRET AXONFLOW_AUTH
export AXONFLOW_USER_TOKEN LLM_MODEL
export AXONFLOW_DB_HOST AXONFLOW_DB_PORT AXONFLOW_DB_USER AXONFLOW_DB_PASSWORD AXONFLOW_DB_NAME

require_stack() {
  if ! command -v python3 &>/dev/null; then
    echo "FAIL: python3 not on PATH — cannot run runtime-e2e tests"
    exit 1
  fi
  if ! curl -sf --max-time 5 "${AXONFLOW_ENDPOINT}/health" &>/dev/null; then
    echo "FAIL: AxonFlow stack not reachable at ${AXONFLOW_ENDPOINT} — runtime-e2e tests require a live stack"
    exit 1
  fi
}

require_psql() {
  if ! command -v psql &>/dev/null; then
    echo "FAIL: psql not on PATH — runtime-e2e tests require psql for DB assertions"
    exit 1
  fi
}

require_hitl() {
  local status
  status=$(curl -sf -H "Authorization: Basic ${AXONFLOW_AUTH}" \
    "${AXONFLOW_ENDPOINT}/api/v1/hitl/status" 2>/dev/null || echo "")
  local enabled
  enabled=$(echo "$status" | python3 -c "import sys,json; print(json.load(sys.stdin).get('enabled',False))" 2>/dev/null || echo "false")
  if [ "$enabled" != "True" ] && [ "$enabled" != "true" ]; then
    echo "FAIL: HITL is not enabled on this stack. Run with eval-tier license."
    echo "  Setup: cd axonflow-enterprise && ./scripts/setup-e2e-testing.sh evaluation"
    echo "  HITL status: $status"
    exit 1
  fi
}

run_psql() {
  PGPASSWORD="$AXONFLOW_DB_PASSWORD" psql \
    -h "$AXONFLOW_DB_HOST" \
    -p "$AXONFLOW_DB_PORT" \
    -U "$AXONFLOW_DB_USER" \
    -d "$AXONFLOW_DB_NAME" \
    -t -A "$@"
}

axonflow_api() {
  local method="$1"
  local path="$2"
  shift 2
  curl -sf -X "$method" \
    -H "Authorization: Basic ${AXONFLOW_AUTH}" \
    -H "Content-Type: application/json" \
    "${AXONFLOW_ENDPOINT}${path}" "$@"
}

create_deny_policy() {
  local name="$1"
  local pattern="$2"
  axonflow_api POST "/api/v1/static-policies" \
    -d "{
      \"name\": \"${name}\",
      \"description\": \"E2E test deny policy\",
      \"category\": \"security-sqli\",
      \"tier\": \"tenant\",
      \"pattern\": \"${pattern}\",
      \"action\": \"block\",
      \"severity\": \"critical\",
      \"enabled\": true
    }"
}

create_require_approval_policy() {
  local name="$1"
  local pattern="$2"
  axonflow_api POST "/api/v1/static-policies" \
    -d "{
      \"name\": \"${name}\",
      \"description\": \"E2E test require_approval policy\",
      \"category\": \"sensitive-data\",
      \"tier\": \"tenant\",
      \"pattern\": \"${pattern}\",
      \"action\": \"require_approval\",
      \"severity\": \"high\",
      \"enabled\": true
    }"
}

wait_for_policy_active() {
  local query="$1"
  local expected_block_reason="${2:-}"
  local br=""
  local i
  for i in $(seq 1 15); do
    local raw_response
    raw_response=$(axonflow_api POST "/api/policy/pre-check" \
      -d "{\"user_token\":\"${AXONFLOW_USER_TOKEN}\",\"query\":\"${query}\",\"client_id\":\"${AXONFLOW_CLIENT_ID}\",\"context\":{}}" 2>/dev/null) || raw_response=""
    br=$(echo "$raw_response" | python3 -c "import sys,json; print(json.load(sys.stdin).get('block_reason',''))" 2>/dev/null) || br=""
    if [ -n "$br" ]; then
      if [ -z "$expected_block_reason" ] || [ "$br" = "$expected_block_reason" ]; then
        echo "$br"
        return 0
      fi
    fi
    sleep 1
  done
  echo ""
  return 0
}

delete_policy() {
  local policy_id="$1"
  axonflow_api DELETE "/api/v1/static-policies/${policy_id}" || true
}

approve_hitl_request() {
  local request_id="$1"
  axonflow_api POST "/api/v1/hitl/queue/${request_id}/approve" \
    -d '{"reviewer_id": "e2e-test-reviewer", "comments": "auto-approved by e2e test"}'
}

reject_hitl_request() {
  local request_id="$1"
  axonflow_api POST "/api/v1/hitl/queue/${request_id}/reject" \
    -d '{"reviewer_id": "e2e-test-reviewer", "comments": "rejected by e2e test"}'
}
